SistGesTurnosHistoriasClinicas/SistGesTurnosHistoriasClinicas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Autenticacion.urls')),
    path('', include('SitioWeb.urls')),
    path('', include('fichero.urls'))
]

SistGesTurnosHistoriasClinicas/fichero/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import *

urlpatterns = [
    path('paciente/', PacientesView.as_view(), name="pacientes"),
    path('paciente/agregar/', AgregarPacienteView.as_view(), name="agregar_pacientes"),
    path('paciente/<int:pk>/editar/', EditarPacienteView.as_view(), name="editar_paciente"),
    path('paciente/<int:pk>/borrar/', BorrarPacienteView.as_view(), name="borrar_paciente"),
    path('paciente/<int:pk>/historiaclinica/', BorrarPacienteView.as_view(), name="historia_clinica"),

    path('medico/', MedicosView.as_view(), name="medicos"),
    path('medico/agregar/', AgregarMedicoView.as_view(), name="agregar_medico"),
    path('medico/agregar/<str:dni>/<str:correo_electronico>/', AgregarMedicoView.as_view(), name="cargar_perfil_medico"),
    path('medico/<int:pk>/editar/', EditarMedicoView.as_view(), name="editar_medico"),

    path('turnos/', TurnoConsultorioView.as_view(), name='turnos_consultorio'),
    path('consultorio/agregar/', AgregarTurnoConsultorioView.as_view(), name='agregar_turno_consultorio'),
    path('consultorio/<int:pk>/editar/', EditarTurnoConsultorioView.as_view(), name='editar_turno_consultorio'),
    path('consultorio/<int:pk>/borrar/', EditarTurnoConsultorioView.as_view(), name="borrar_turno_consultorio"),
    path('consultorio/agregar/<str:fecha>/<str:medico>/', AgregarTurnoConsultorioView.as_view(), name='agregar_turno_consultorio_medico'),
]
    
    

SistGesTurnosHistoriasClinicas/fichero/models.py
from datetime import datetime
from crum import get_current_user
from django.db import models
from django.http import HttpResponseRedirect
from django.urls import reverse
from Autenticacion.models import Usuario
from django.core import serializers


class BaseAuditoria(models.Model):
    borrado = models.BooleanField(default=False)
    creado_fecha = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    creado_usuario = models.CharField(max_length=50, null=True, blank=True)
    modificado_fecha = models.DateTimeField(null=True, blank=True)
    modificado_usuario = models.CharField(max_length=50, null=True, blank=True)
    borrado_fecha = models.DateTimeField(null=True, blank=True)
    borrado_usuario = models.CharField(max_length=50, null=True, blank=True)
    modificaciones = models.TextField(default = '', verbose_name='MODIFICACIONES')


    class Meta:
        abstract = True

class Paciente(BaseAuditoria):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    dni = models.CharField(max_length=50, unique=True, verbose_name='DNI')
    apellido = models.CharField(max_length=150, verbose_name='APELLIDO')
    nombre = models.CharField(max_length=150, verbose_name='NOMBRE')
    fecha_de_nacimiento = models.DateField(verbose_name='NACIMIENTO')
    correo_electronico = models.EmailField(verbose_name='CORREO_ELECTRONICO')
    pais = models.CharField(max_length=50, verbose_name='PAIS')
    provincia = models.CharField(max_length=50, verbose_name='PROVINCIA')
    localidad = models.CharField(max_length=50, verbose_name='LOCALIDAD')
    direccion = models.CharField(max_length=50, verbose_name='DIRECCION')
    telefono = models.CharField(max_length=50, verbose_name='TELEFONO')
    contacto = models.CharField(max_length=150, verbose_name='CONTACTO')
    antecedentes = models.TextField(null=True, default="")

    def __str__(self):
        return str(self.apellido) + ', ' + str(self.nombre)

    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not Paciente.objects.filter(dni=self.dni).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores_jason = serializers.serialize('json', Paciente.objects.filter(pk=self.pk))
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(Paciente, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pacientes')

class Medico(BaseAuditoria):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    dni = models.CharField(max_length=50, unique=True, verbose_name='DNI')
    apellido = models.CharField(max_length=150, verbose_name='APELLIDO')
    nombre = models.CharField(max_length=150, verbose_name='NOMBRE')
    correo_electronico = models.EmailField(verbose_name='CORREO_ELECTRONICO')
    telefono = models.CharField(max_length=50, verbose_name='TELEFONO')
    matricula = models.CharField(max_length=50, verbose_name='MATRICULA_PROFESIONAL')

    def __str__(self):
            return str(self.apellido) + ', ' + str(self.nombre)

    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not Medico.objects.filter(dni=self.dni).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores_jason = serializers.serialize('json', Medico.objects.filter(pk=self.pk))
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(Medico, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pacientes')

class BaseTurno(BaseAuditoria):
    ESTADO = (
        ('AUSENTE', 'Ausente'),
        ('EN ESPERA', 'En espera'),
        ('ATENDIENDO', 'Atendiendo'),
        ('ATENDIDO', 'Atendido'),
    )

    fecha = models.DateField(null=False, blank=False, verbose_name='FECHA')
    hora = models.TimeField(null=False, blank=False, verbose_name='HORA')
    estado = models.CharField(max_length=50, null=False, blank=False, default='AUSENTE', verbose_name='ESTADO', choices=ESTADO)
    observaciones = models.TextField(null=True, blank=True, verbose_name='OBSERVACIONES')
    class Meta:
        abstract = True

class TurnoConsultorio(BaseTurno):
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='MEDICO', related_name='consultorio_medico_related')
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='PACIENTE', related_name='consultorio_paciente_related')
    mediciones_realizadas = models.TextField(null=True, blank=True, verbose_name='MEDICIONES_REALIZADAS')
    motivo_consulta = models.TextField(null=True, blank=True, verbose_name='MOTIVO_CONSULTA')
    diagnostico = models.TextField(null=True, blank=True, verbose_name='DIAGNOSTICO')
    tratamiento = models.TextField(null=True, blank=True, verbose_name='TRATAMIENTO')
    
    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not TurnoConsultorio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores = TurnoConsultorio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico)
                datos_anteriores_jason = serializers.serialize('json', datos_anteriores)
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #recupero el turno si es que fue borrado y se lo quiere volver a crear
                if datos_anteriores.borrado:
                    self.borrado = False

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(TurnoConsultorio, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('turnos_consultorio')

class TurnoEstudio(BaseTurno):
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='MEDICO', related_name='estudio_medico_related')
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='PACIENTE', related_name='estudio_paciente_related')
    nombre_estudio = models.TextField(null=True, blank=True, verbose_name='NOMBRE_ESTUDIO')
    ubicacion_archivo = models.TextField(null=True, blank=True, verbose_name='UBICACIÓN_ARCHIVO')
    hash_archivo = models.TextField(null=True, blank=True, verbose_name='HASH_ARCHIVO')
    
    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not TurnoEstudio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores = TurnoEstudio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico)
                datos_anteriores_jason = serializers.serialize('json', datos_anteriores)
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #recupero el turno si es que fue borrado y se lo quiere volver a crear
                if datos_anteriores.borrado:
                    self.borrado = False

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:                    
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(TurnoEstudio, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('turnos_estudio')

class HistoriaClinica(BaseAuditoria):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=False, blank=False,

SistGesTurnosHistoriasClinicas/fichero/forms.py
from django import forms

from .models import *

#--> PACIENTES

class AgregarPacienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AgregarPacienteForm, self).__init__(*args, **kwargs)
        self.fields['contacto'].required = False

    class Meta:
        model = Paciente
        fields = ('dni', 'apellido', 'nombre', 'fecha_de_nacimiento',
                  'pais', 'provincia', 'localidad', 'direccion',
                  'telefono', 'contacto', )

        widgets = {
            'dni': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DNI (solo numeros)'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido/s'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre/s'}),
            'fecha_de_nacimiento': forms.DateInput(format='%d/%m/%Y',
                                          attrs={'class': 'form-control', 'placeholder': 'Naciemiento (dd/mm/aaaa)'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-control',}),
            'pais': forms.TextInput(attrs={'class': 'form-control', 'value': 'Argentina'}),
            'provincia': forms.TextInput(attrs={'class': 'form-control', 'value': 'Chaco'}),
            'localidad': forms.TextInput(attrs={'class': 'form-control', 'value': 'Resistencia'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dirección'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Teléfono'}),
            'contacto': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Datos del Contacto: Nom., Ape. y Tel.'}),
            
        }

class BorrarPacienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BorrarPacienteForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Paciente
        fields = ('dni', 'apellido', 'nombre', 'fecha_de_nacimiento',
                  'pais', 'provincia', 'localidad', 'direccion',
                  'telefono', 'contacto', 'borrado')

        widgets = {
            'dni': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'fecha_de_nacimiento': forms.DateInput(format='%d/%m/%Y',
                                          attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'correo_electronico': forms.EmailInput(attrs={ 'readonly': 'readonly', 'class': 'form-control',}),
            'pais': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'provincia': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'localidad': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'contacto': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
        }

#--> MEDICOS

class AgregarMedicoForm(forms.ModelForm):
    
    class Meta:
        model = Medico
        fields = ('dni', 'apellido', 'nombre', 'correo_electronico',
                  'telefono', 'matricula', )

        widgets = {
            'dni': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DNI (solo numeros)'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido/s'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre/s'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-control',}),
            'telefono': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Teléfono'}),
            'matricula': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Número de matrícula'}),
            
        }

#--> TURNOS CONSULTORIO

class AgregarTurnoConsultorioForm(forms.ModelForm):
    
    class Meta:
        model = TurnoConsultorio
        fields = ('fecha', 'hora', 'medico', 'paciente', 'borrado')

        widgets = {
            'fecha': forms.DateInput(format='%d/%m/%Y'),
            'hora': forms.TimeInput(format='%H/%M'),   
            'medico': forms.NumberInput(),
            'paciente': forms.NumberInput(),         
        }

class BorrarTurnoConsultorioForm(forms.ModelForm):
    
    class Meta:
        model = TurnoConsultorio
        fields = ('fecha', 'hora', 'medico', 'paciente', 'borrado')

        widgets = {
            'fecha': forms.DateInput(format='%d/%m/%Y'),
            'hora': forms.TimeInput(format='%H/%M'),   
            'medico': forms.NumberInput(),
            'paciente': forms.NumberInput(),         
        }

SistGesTurnosHistoriasClinicas/fichero/templates/medicos/medicos.html
{% extends 'base.html' %}
{% block title %} - Médicos {% endblock %}

{% block content %}

    <h1>Médicos</h1>
    <div>
        <button type="button" class="btn btn-light" onclick="location.href='{% url 'agregar_medico' %}'">Nuevo Médico</button>
    </div>


    <h2>Buscar Médico</h2>
    <form method="get" action=".">
        <div class="row">
            <div class="col">
                {{ filter.form }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button class="btn btn-secondary" type="submit">Buscar</button>
            </div>
        </div>
    </form>



    <div>
    <!-- {% if user.is_authenticated %} -->
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        D.N.I.
                    </th>
                    <th>
                        APELLIDO
                    </th>
                    <th>
                        NOMBRE
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            {% for Medico in object_list %}
                {% if Medico.borrado == False %}
                        <tr>
                            <th>
                                <a href="{% url 'editar_medico' Medico.pk %}">
                                    {{ Medico.dni }}
                                </a>
                            </th>
                            <th>
                                {{ Medico.apellido }}
                            </th>
                            <th>
                                {{ Medico.nombre }}
                            </th>
                            <th>
                                <a href="{% url 'editar_medico' Medico.pk %}"> Historia Clínica</a><br/>
                                <a class="text-warning" href="{% url 'editar_medico' Medico.pk %}"> Edit</a>
                                <!-- <a class="text-danger" href="{% url 'editar_medico' Medico.pk %}"> Eliminar </a> -->
                            </th>
                        </tr>
                {% else %}
                    {% if user.groups.all.0.name == "administradores" %} 
                        <tr>
                            <th>
                                {{ Medico.dni }}
                            </th>
                            <th>
                                {{ Medico.apellido }}
                            </th>
                            <th>
                                {{ Medico.nombre }}
                            </th>
                            <th>
                                <!-- <a href="{% url 'editar_medico' Medico.pk %}"> Recuperar </a> -->
                            </th>
                        </tr>
                   {% endif %}
               {% endif %}
            {% endfor %}
        </table>
        <div>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    {% if page_obj.previous_page_number != 1 %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">1</a>
                        </li>
                        <li class="page-item">
                            ...
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    </li>
                {% endif %}

                <li class="page-item">
                    <a class="page-link" href="#">{{ page_obj.number }}</a>
                </li>
                {% if page_obj.has_next %}
                    {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        </li>
                        <li class="page-item">
                            ...
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    <!-- {% else %}
        <h1>NO TENES PERMISO PARA ELLO</h1>
    {% endif %} -->
    </div>
{% endblock %}

SistGesTurnosHistoriasClinicas/fichero/templates/medicos/perfil_medico.html
{% extends 'base.html' %}
{% block title %} Administrar datos del Médico {% endblock %}

{% block content %}
    <!-- {% if user.is_authenticated %} -->

        <h1>Datos del Médico</h1>
        <div class="form-group">
            <form method="post">
                {% csrf_token %}
                <!-- {{ form.as_p }}
                <button class="btn btn-secondary">Guardar</button> -->
                <label for="id_dni">DNI:</label>
                <input type="text" name="dni" class="form-control" placeholder="DNI (solo numeros)" maxlength="50" required id="id_dni"
                {% if dni %} value="{{ dni }}" {% endif %}
                {% if medico %} value="{{ medico.dni }}" {% endif %}>
    
                <label for="id_apellido">APELLIDO:</label>
                <input type="text" name="apellido" class="form-control" placeholder="Apellido/s" maxlength="150" required id="id_apellido"
                {% if medico %} value="{{ medico.apellido }}" {% endif %}>
    
                <label for="id_nombre">NOMBRE:</label>
                <input type="text" name="nombre" class="form-control" placeholder="Nombre/s" maxlength="150" required id="id_nombre"
                {% if medico %} value="{{ medico.nombre }}" {% endif %}>
    
                <label for="id_correo_electronico">CORREO_ELECTRONICO:</label>
                <input type="email" name="correo_electronico" class="form-control" maxlength="254" required id="id_correo_electronico" 
                {% if correo_electronico %}value="{{ correo_electronico }}" {% endif %}
                {% if medico %} value="{{ medico.correo_electronico }}" {% endif %}>
    
                <label for="id_telefono">TELEFONO:</label>
                <input type="text" name="telefono" class="form-control" placeholder="Teléfono" maxlength="50" required id="id_telefono"
                {% if medico %} value="{{ medico.telefono }}" {% endif %}>
    
                <label for="id_matricula">MATRICULA_PROFESIONAL:</label>
                <input type="text" name="matricula" class="form-control" placeholder="Número de matrícula" maxlength="50" required id="id_matricula"
                {% if medico %} value="{{ medico.matricula }}" {% endif %}>
    
                <button type="submit" class="btn btn-secondary">Guardar</button>
            </form>
        </div>
    <!-- {% else %}
        <h1>NO TENES PERMISO PARA ELLO</h1>
    {% endif %} -->

{% endblock %}