SistGesTurnosHistoriasClinicas/SistGesTurnosHistoriasClinicas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Autenticacion.urls')),
    path('', include('SitioWeb.urls')),
    path('', include('fichero.urls'))
]

SistGesTurnosHistoriasClinicas/fichero/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import *

urlpatterns = [
    path('paciente/', PacientesView.as_view(), name="pacientes"),
    path('paciente/agregar/', AgregarPacienteView.as_view(), name="agregar_pacientes"),
    path('paciente/<int:pk>/editar/', EditarPacienteView.as_view(), name="editar_paciente"),
    path('paciente/<int:pk>/borrar/', BorrarPacienteView.as_view(), name="borrar_paciente"),
    path('paciente/<int:pk>/historiaclinica/', BorrarPacienteView.as_view(), name="historia_clinica"),

    path('medico/', MedicosView.as_view(), name="medicos"),
    path('medico/agregar/', AgregarMedicoView.as_view(), name="agregar_medico"),
    path('medico/agregar/<str:dni>/<str:correo_electronico>/', AgregarMedicoView.as_view(), name="cargar_perfil_medico"),
    path('medico/<int:pk>/editar/', EditarMedicoView.as_view(), name="editar_medico"),

    path('turnos/', TurnoConsultorioView.as_view(), name='turnos_consultorio'),
    path('consultorio/agregar/', AgregarTurnoConsultorioView.as_view(), name='agregar_turno_consultorio'),
    path('consultorio/<int:pk>/editar/', EditarTurnoConsultorioView.as_view(), name='editar_turno_consultorio'),
    path('consultorio/<int:pk>/borrar/', EditarTurnoConsultorioView.as_view(), name="borrar_turno_consultorio"),
    path('consultorio/agregar/<str:fecha>/<str:medico>/', AgregarTurnoConsultorioView.as_view(), name='agregar_turno_consultorio_medico'),
]
    
    

SistGesTurnosHistoriasClinicas/fichero/models.py
from datetime import datetime
from crum import get_current_user
from django.db import models
from django.http import HttpResponseRedirect
from django.urls import reverse
from Autenticacion.models import Usuario
from django.core import serializers


class BaseAuditoria(models.Model):
    borrado = models.BooleanField(default=False)
    creado_fecha = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    creado_usuario = models.CharField(max_length=50, null=True, blank=True)
    modificado_fecha = models.DateTimeField(null=True, blank=True)
    modificado_usuario = models.CharField(max_length=50, null=True, blank=True)
    borrado_fecha = models.DateTimeField(null=True, blank=True)
    borrado_usuario = models.CharField(max_length=50, null=True, blank=True)
    modificaciones = models.TextField(default = '', verbose_name='MODIFICACIONES')


    class Meta:
        abstract = True

class Paciente(BaseAuditoria):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    dni = models.CharField(max_length=50, unique=True, verbose_name='DNI')
    apellido = models.CharField(max_length=150, verbose_name='APELLIDO')
    nombre = models.CharField(max_length=150, verbose_name='NOMBRE')
    fecha_de_nacimiento = models.DateField(verbose_name='NACIMIENTO')
    correo_electronico = models.EmailField(verbose_name='CORREO_ELECTRONICO')
    pais = models.CharField(max_length=50, verbose_name='PAIS')
    provincia = models.CharField(max_length=50, verbose_name='PROVINCIA')
    localidad = models.CharField(max_length=50, verbose_name='LOCALIDAD')
    direccion = models.CharField(max_length=50, verbose_name='DIRECCION')
    telefono = models.CharField(max_length=50, verbose_name='TELEFONO')
    contacto = models.CharField(max_length=150, verbose_name='CONTACTO')
    antecedentes = models.TextField(null=True, default="")

    def __str__(self):
        return str(self.apellido) + ', ' + str(self.nombre)

    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not Paciente.objects.filter(dni=self.dni).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores_jason = serializers.serialize('json', Paciente.objects.filter(pk=self.pk))
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(Paciente, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pacientes')

class Medico(BaseAuditoria):
    id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    dni = models.CharField(max_length=50, unique=True, verbose_name='DNI')
    apellido = models.CharField(max_length=150, verbose_name='APELLIDO')
    nombre = models.CharField(max_length=150, verbose_name='NOMBRE')
    correo_electronico = models.EmailField(verbose_name='CORREO_ELECTRONICO')
    telefono = models.CharField(max_length=50, verbose_name='TELEFONO')
    matricula = models.CharField(max_length=50, verbose_name='MATRICULA_PROFESIONAL')

    def __str__(self):
            return str(self.apellido) + ', ' + str(self.nombre)

    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not Medico.objects.filter(dni=self.dni).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores_jason = serializers.serialize('json', Medico.objects.filter(pk=self.pk))
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(Medico, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pacientes')

class BaseTurno(BaseAuditoria):
    ESTADO = (
        ('AUSENTE', 'Ausente'),
        ('EN ESPERA', 'En espera'),
        ('ATENDIENDO', 'Atendiendo'),
        ('ATENDIDO', 'Atendido'),
    )

    fecha = models.DateField(null=False, blank=False, verbose_name='FECHA')
    hora = models.TimeField(null=False, blank=False, verbose_name='HORA')
    estado = models.CharField(max_length=50, null=False, blank=False, default='AUSENTE', verbose_name='ESTADO', choices=ESTADO)
    observaciones = models.TextField(null=True, blank=True, verbose_name='OBSERVACIONES')
    class Meta:
        abstract = True

class TurnoConsultorio(BaseTurno):
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='MEDICO', related_name='consultorio_medico_related')
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='PACIENTE', related_name='consultorio_paciente_related')
    mediciones_realizadas = models.TextField(null=True, blank=True, verbose_name='MEDICIONES_REALIZADAS')
    motivo_consulta = models.TextField(null=True, blank=True, verbose_name='MOTIVO_CONSULTA')
    diagnostico = models.TextField(null=True, blank=True, verbose_name='DIAGNOSTICO')
    tratamiento = models.TextField(null=True, blank=True, verbose_name='TRATAMIENTO')
    
    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not TurnoConsultorio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores = TurnoConsultorio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico)
                datos_anteriores_jason = serializers.serialize('json', datos_anteriores)
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #recupero el turno si es que fue borrado y se lo quiere volver a crear
                if datos_anteriores.borrado:
                    self.borrado = False

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(TurnoConsultorio, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('turnos_consultorio')

class TurnoEstudio(BaseTurno):
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='MEDICO', related_name='estudio_medico_related')
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=False, blank=False,
                            verbose_name='PACIENTE', related_name='estudio_paciente_related')
    nombre_estudio = models.TextField(null=True, blank=True, verbose_name='NOMBRE_ESTUDIO')
    ubicacion_archivo = models.TextField(null=True, blank=True, verbose_name='UBICACIÓN_ARCHIVO')
    hash_archivo = models.TextField(null=True, blank=True, verbose_name='HASH_ARCHIVO')
    
    def save(self, *args, **kwargs):
        usuario = get_current_user()
        if usuario is not None:
            if not TurnoEstudio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico).exists():
                #registro la creación
                self.creado_fecha = datetime.now()
                self.creado_usuario = usuario.dni
            else:
                #Guardo los datos previos a la modificación. 
                datos_anteriores = TurnoEstudio.objects.filter(fecha=self.fecha, hora=self.hora, medico=self.medico)
                datos_anteriores_jason = serializers.serialize('json', datos_anteriores)
                self.modificaciones = 'version anterior - ' + datetime.now().strftime("%m/%d/%Y, %H:%M:%S") + '\n' + datos_anteriores_jason

                #recupero el turno si es que fue borrado y se lo quiere volver a crear
                if datos_anteriores.borrado:
                    self.borrado = False

                #registro la modificación o eliminación lógica
                if self.borrado:
                    self.borrado_fecha = datetime.now()
                    self.borrado_usuario = usuario.dni
                else:                    
                    self.modificado_fecha = datetime.now()
                    self.modificado_usuario = usuario.dni    
        super(TurnoEstudio, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('turnos_estudio')

class HistoriaClinica(BaseAuditoria):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=False, blank=False,

SistGesTurnosHistoriasClinicas/fichero/forms.py
from django import forms

from .models import *

#--> PACIENTES

class AgregarPacienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AgregarPacienteForm, self).__init__(*args, **kwargs)
        self.fields['contacto'].required = False

    class Meta:
        model = Paciente
        fields = ('dni', 'apellido', 'nombre', 'fecha_de_nacimiento',
                  'pais', 'provincia', 'localidad', 'direccion',
                  'telefono', 'contacto', )

        widgets = {
            'dni': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DNI (solo numeros)'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido/s'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre/s'}),
            'fecha_de_nacimiento': forms.DateInput(format='%d/%m/%Y',
                                          attrs={'class': 'form-control', 'placeholder': 'Naciemiento (dd/mm/aaaa)'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-control',}),
            'pais': forms.TextInput(attrs={'class': 'form-control', 'value': 'Argentina'}),
            'provincia': forms.TextInput(attrs={'class': 'form-control', 'value': 'Chaco'}),
            'localidad': forms.TextInput(attrs={'class': 'form-control', 'value': 'Resistencia'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dirección'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Teléfono'}),
            'contacto': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Datos del Contacto: Nom., Ape. y Tel.'}),
            
        }

class BorrarPacienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BorrarPacienteForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Paciente
        fields = ('dni', 'apellido', 'nombre', 'fecha_de_nacimiento',
                  'pais', 'provincia', 'localidad', 'direccion',
                  'telefono', 'contacto', 'borrado')

        widgets = {
            'dni': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'fecha_de_nacimiento': forms.DateInput(format='%d/%m/%Y',
                                          attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'correo_electronico': forms.EmailInput(attrs={ 'readonly': 'readonly', 'class': 'form-control',}),
            'pais': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'provincia': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'localidad': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'contacto': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
        }

#--> MEDICOS

class AgregarMedicoForm(forms.ModelForm):
    
    class Meta:
        model = Medico
        fields = ('dni', 'apellido', 'nombre', 'correo_electronico',
                  'telefono', 'matricula', )

        widgets = {
            'dni': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'DNI (solo numeros)'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido/s'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre/s'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-control',}),
            'telefono': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Teléfono'}),
            'matricula': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'Número de matrícula'}),
            
        }

#--> TURNOS CONSULTORIO

class AgregarTurnoConsultorioForm(forms.ModelForm):
    
    class Meta:
        model = TurnoConsultorio
        fields = ('fecha', 'hora', 'medico', 'paciente', 'borrado')

        widgets = {
            'fecha': forms.DateInput(format='%d/%m/%Y'),
            'hora': forms.TimeInput(format='%H/%M'),   
            'medico': forms.NumberInput(),
            'paciente': forms.NumberInput(),         
        }

class BorrarTurnoConsultorioForm(forms.ModelForm):
    
    class Meta:
        model = TurnoConsultorio
        fields = ('fecha', 'hora', 'medico', 'paciente', 'borrado')

        widgets = {
            'fecha': forms.DateInput(format='%d/%m/%Y'),
            'hora': forms.TimeInput(format='%H/%M'),   
            'medico': forms.NumberInput(),
            'paciente': forms.NumberInput(),         
        }

SistGesTurnosHistoriasClinicas/fichero/templates/turnos/agregar_turno_consultorio.html
{% extends 'base.html' %}
{% block title %} Administrar datos del Paciente {% endblock %}

{% block content %}
    
<div class="row">
    <h1>Agregar Turno para consultorio</h1>
</div>
<form method="get" action=".">
    <input type="number" hidden name="refresh" id="id_refresh" value="{{ refresh }}">
    <div class="form-group" {% if siguiente == 'Siguiente' %} hidden {% endif %}>
        <div class="row">
            <div class="col-sm-3">
                <div class="container p-3 my-3 border">            
                    <div class="form-group py-2">
                        <h4>Seleccione fecha</h4>
                        <input type="date" class="form-control" name="fecha" id="id_fecha" value="{{ fecha_selecta2 }}">
                    </div>
                    <div class="form-group py-2">
                        <h4>Seleccione hora</h4>
                        <input type="time" class="form-control" name="hora"  id="id_hora" value="{{ hora_selecta }}">
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="container p-3 my-3 border">            
                    <div class="form-group py-2">
                        <h4>Seleccione el médico</h4>
                        {% for medico in medicos %}
                            <div class="form-check">
                                <input type="radio" name="medico" id="id_medico" class="form-check-input" value="{{ medico.pk }}" {% if medico_selecto == medico.pk %} checked {% endif %} >
                                <label class="form-check-label" for="id_medico">{{ medico }}</label>
                            </div>                       
                        {% endfor %}
                    </div>            
                </div>
            </div>
            <div class="col-sm-6">
                <div class="container p-3 my-3 border"> 
                    <h4>Seleccione el paciente</h4>
                    <div class="row">
                        <div class="col">
                            <input type="text" class="form-control" name="paciente_dni" placeholder="DNI (solo numeros)" value="{{ paciente_dni }}">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" name="paciente_apellido" placeholder="Apellido" value="{{ paciente_apellido }}">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" name="paciente_nombre" placeholder="Nombre" value="{{ paciente_nombre }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group py-2">
                            <button class="form-control btn btn-secondary" type="submit">Buscar</button>                        
                        </div>
                    </div> 
                    <div class="row">                    
                        <div class="col-1">
                        </div>
                        <div class="col">DNI</div>
                        <div class="col">APELLIDO</div>
                        <div class="col">NOMBRE</div>
                        <div class="col">TELEFONO</div>
                    </div>  
                    {% for paciente in pacientes %}
                    <div class="row">           
                        <div class="col-1">
                            <input type="radio" name="paciente" id="id_paciente" class="form-check-input" value="{{ paciente.pk }}" {% if paciente_selecto == paciente.pk %} checked {% endif %} >
                        </div>
                        <div class="col">{{ paciente.dni }}</div>
                        <div class="col">{{ paciente.apellido }}</div>
                        <div class="col">{{ paciente.nombre }}</div>
                        <div class="col">{{ paciente.telefono }}</div>                    
                    </div>                        
                    {% endfor %}      
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-12">
                <div class="container p-3 my-3 border"> 
                    <input type="checkbox" name="borrado" id="id_borrado" {% if borrado == True %} checked {% endif %}>
                    <label class="text-danger">BORRAR TURNO</label>                
                </div>
            </div>
        </div>

    </div>  
    <div class="row">
        <div class="col-sm-12">
            <div class="container p-3 my-3 border"> 
                <input class="form-control btn btn-secondary" type="submit" 
                {% if siguiente == "Cambiar" %} 
                    value="Siguiente" 
                {% else %}
                    value="Cambiar" 
                {% endif %}            
                name="siguiente">
            </div>
        </div>
    </div> 
</form> 
<div class="row" {% if siguiente != "Siguiente" %} hidden {% endif %}>
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
        <div class="container p-3 my-3 border">
            <div class="form-group">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group py-2">
                        <input type="text" readonly class="form-control" name="fecha" required id="id_fecha" value="{{fecha_selecta}}">
                    </div>
                    <div class="form-group py-2">
                        <input type="text" readonly class="form-control py-2" name="hora" required id="id_hora" value="{{ hora_selecta }}">
                    </div>
                    <div class="form-group py-2">
                        <input type="number" readonly class="form-control py-2" name="medico" required id="id_medico" value="{{ medico_selecto }}">
                    </div>
                    <div class="form-group py-2">
                        <input type="number" readonly class="form-control py-2" name="paciente" required id="id_paciente" value="{{ paciente_selecto }}">
                    </div>
                    <div class="form-group py-2">
                        <input type="checkbox" readonly name="borrado" id="id_borrado" {% if borrado == True %} checked {% endif %}>
                        <label class="text-danger">BORRAR TURNO</label>
                    </div>
                    <div class="form-group py-2">
                        <button class="btn btn-secondary form-control py-2">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
        
    

{% endblock %}

SistGesTurnosHistoriasClinicas/fichero/templates/turnos/turnos.html
{% extends 'base.html' %}
{% block title %} Turnos {% endblock %}

{% block content %}

<div class="row">
    <div class="col-sm-3">
        <div class="container p-3 my-3 border">  
            <div class="form-group py-1">
                <input type="button" class="btn btn-light form-control" value="AGREGAR NUEVO TURNO" onclick="location.href='{% url 'agregar_turno_consultorio' %}'" >
            </div>            
        </div>        
        <div class="container p-3 my-3 border">
            <form method="get">
                <div class="form-group py-1">
                    <h4>Seleccione una fecha: </h4>
                    <input type="date" class="form-control" name="fecha_selecta" value="{{ fecha_selecta }}">
                </div>
                <div class="form-group py-1">
                    <h4>Seleccione un médico:</h4>
                    {% for medico in medicos %}
                    <div class="form-check">
                        <input type="radio" name="radio_medico_selecto" class="form-check-input" value="{{ medico.pk }}" {% if medico_selecto == medico.pk %} checked {% endif %} >
                        <label class="form-check-label">{{ medico }}</label>
                    </div>                       
                    {% endfor %}            
                </div>
                <div class="form-group py-1">
                    <input type="submit" class="btn btn-light form-control" value="Actualizar" >
                </div>
            </form>
        </div>
        <div class="container p-3 my-3 border">
            <form method="get">
                <div class="form-group py-1">
                    <h4>Filtro de estados: </h4>                    
                    <div class="form-check">
                        <input type="radio" name="radio_estado_selecto" class="form-check-input" value="TODOS" {% if estado_selecto == 'TODOS' %} checked {% endif %} >
                        <label class="form-check-label">Todos</label>
                    </div>       
                    <div class="form-check">
                        <input type="radio" name="radio_estado_selecto" class="form-check-input" value="AUSENTE" {% if estado_selecto == 'AUSENTE' %} checked {% endif %} >
                        <label class="form-check-label">Ausentes</label>
                    </div>  
                    <div class="form-check">
                        <input type="radio" name="radio_estado_selecto" class="form-check-input" value="EN ESPERA" {% if estado_selecto == 'EN ESPERA' %} checked {% endif %} >
                        <label class="form-check-label">En espera</label>
                    </div>       
                    <div class="form-check">
                        <input type="radio" name="radio_estado_selecto" class="form-check-input" value="ATENDIENDO" {% if estado_selecto == 'ATENDIENDO' %} checked {% endif %} >
                        <label class="form-check-label">Atendiendo</label>
                    </div>                    
                    <div class="form-check">
                        <input type="radio" name="radio_estado_selecto" class="form-check-input" value="ATENDIDO" {% if estado_selecto == 'ATENDIDO' %} checked {% endif %} >
                        <label class="form-check-label">Atendido</label>
                    </div> 
                </div>
                <div class="form-group py-1">
                    <input type="submit" class="btn btn-light form-control" value="Actualizar" >
                </div>
            </form>
        </div>    
    </div>
    <div class="col-sm-9">
        <div class="container p-3 my-3 border">
            <div class="row btn-light">                    
                <div class="col">FECHA</div>
                <div class="col">HORA</div>
                <div class="col">ESTADO</div>
                <div class="col">PACIENTE</div>
                <div class="col"></div>
                <div class="col-1"></div>
            </div>  
            {% for turno in turnos %}
            <div class="row">           
                <div class="col">{{ turno.fecha }}</div>
                <div class="col">{{ turno.hora }}</div>
                <div class="col">{{ turno.estado }}</div>
                <div class="col">{{ turno.paciente }}</div>                    
                <div class="col">
                    <a href="{% url 'historia_clinica' turno.paciente.pk %}"> Historia Clínica</a><br/>
                    <a class="text-warning" href="{% url 'editar_turno_consultorio' turno.pk %}"> Edit</a>
                    <a class="text-danger" href="{% url 'borrar_turno_consultorio' turno.pk %}"> Eliminar </a>
                </div> 
                <div class="col">
                    <button class="form-control btn btn-secondary" type="submit">ATENDER</button>
                </div>                   
            </div>                        
            {% endfor %} 
        </div>
        
    </div>
</div>




{% endblock %}